project: cgm_ignite_feast_kafka
# By default, the registry is a file (but can be turned into a more scalable SQL-backed registry)
registry: data/registry.db
# The provider primarily specifies default offline / online stores & storing the registry in a given cloud
provider: local
online_store:
    type: feast_gridgain.gridgain_online_store.GridGainOnlineStore
    host: ignite
    port: 10800
entity_key_serialization_version: 2