# Use a base image with Python 3.11.7
FROM python:3.11.7

WORKDIR /app

COPY requirements-api.txt requirements-api.txt

# Corrected Path

RUN pip install --no-cache-dir -r requirements-api.txt  # Install all dependencies

COPY src/data /app/data
COPY src/repo /app/repo
COPY src/api.py /app/api.py
COPY src/test_workflow.py /app/test_workflow.py

ENV repo_path=repo/docker
CMD ["sh", "-c", "cd $repo_path && feast apply && cd ../.. && uvicorn api:app --host 0.0.0.0 --port 8000"]
